spring:
  profiles:
    active: dev # default
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common
---
# development
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/prj
    username: "root"
    password: "1221"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
---
# production
spring:
  config:
    activate:
      on-profile: prod
